'use client';
import { useState, useEffect } from 'react';
import './workspace.css';

type Item = { id: string; group: string; title: string; text: string; image: string; status: string };
const initial: Item[] = [
  {id:'hero',group:'首頁管理',title:'為效能而生的先進材料體系',text:'從材料研發到應用驗證，為產品提供更合適的材料方案。',image:'/images/factory-production-line-hero.png',status:'展示'},
  ...['鞋材','中底','鞋墊','運動護具'].map((title,i)=>({id:'scene'+i,group:'首頁管理',title,text:'應用場景介紹，可在此修改卡片文案。',image:'/images/'+['application-footwear-v2.png','application-midsole.png','application-insole.png','application-protective-gear.png'][i],status:'展示'})),
  ...['IUS-4065','LF-ET78A','LF-HR53A','GTE-8030','GTE-8075'].map((title,i)=>({id:'product'+i,group:'產品管理',title,text:i===0?'硬度：Shore A 40\n熔點：約 64°C\n超柔軟 · 更高熔點 · 更穩定加工':i===1?'硬度：Shore A 78\n熔點：69°C\n高分散型 TPE 彈性材料':'資料待補充',image:'/images/'+(i===0?'ius-4065-white-pellets-v4-scattered.png':'lf-et78a-product.png'),status:i<2?'展示':'草稿'})),
  ...['如何為產品選擇合適的 TPE 材料？','發泡 TPE 開發，需要關注哪些指標？','從試料到量產，如何推進材料開發？'].map((title,i)=>({id:'article'+i,group:'文章管理',title,text:'從應用場景到目標效能，梳理材料開發需要準備的資訊。\n\n這裡是文章正文編輯演示，可修改後檢視右側預覽。',image:'/images/'+['blog-selection-v2.png','blog-foam-v2.png','blog-validation-v2.png'][i],status:'展示'}))
];
const menus=['工作臺','首頁管理','產品管理','文章管理','素材與資料','客戶詢盤','網站設定','賬號與許可權'];
export default function Admin(){
 const [section,setSection]=useState('首頁管理'); const [items,setItems]=useState(initial); const [selected,setSelected]=useState('hero');
 const [draft,setDraft]=useState<Item>(initial[0]); const [search,setSearch]=useState(''); const [notice,setNotice]=useState(''); const [tab,setTab]=useState('內容編輯'); const [history,setHistory]=useState<string[]>([]);
 const saved=items.find(x=>x.id===selected); const dirty=!!saved&&JSON.stringify(saved)!==JSON.stringify(draft);
 useEffect(()=>{ const h=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h);},[dirty]);
 const leave=()=>!dirty||window.confirm('當前修改尚未儲存，確定放棄並切換嗎？');
 function navigate(name:string){if(!leave())return;setSection(name);setSearch('');setNotice('');const first=items.find(x=>x.group===name);if(first){setSelected(first.id);setDraft({...first});}else if(saved)setDraft({...saved});}
 function select(item:Item){if(!leave())return;setSelected(item.id);setDraft({...item});setNotice('');}
 function save(){if(!draft.title.trim()){setNotice('請填寫標題。');return;}setItems(items.map(x=>x.id===selected?{...draft}:x));setHistory([draft.title,...history].slice(0,5));setNotice('已儲存到本次演示會話。重新整理後重置，未更新線上網站。');}
 function add(){if(!leave())return;const item={id:String(Date.now()),group:section,title:section==='文章管理'?'未命名文章':'新產品',text:'',image:'/images/blog-selection-v2.png',status:'草稿'};setItems([...items,item]);setSelected(item.id);setDraft(item);}
 async function upload(file?:File){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){setNotice('請選擇 5 MB 以內的 JPG、PNG 或 WebP 圖片。');return;}const reader=new FileReader();reader.onload=()=>{setDraft(d=>({...d,image:String(reader.result)}));setNotice('圖片已用於本次預覽，尚未儲存。');};reader.readAsDataURL(file);}
 const filtered=items.filter(x=>x.group===section&&x.title.toLowerCase().includes(search.toLowerCase()));
 return <div className="cms"><aside className="cms-side"><a href="/" className="cms-brand"><b>LF</b><span>LEAD FAIR<small>MATERIALS STUDIO</small></span></a><div className="cms-site">原料研發網站 <span>內容工作區</span></div><nav aria-label="後臺導航">{menus.map((name,i)=><button key={name} aria-current={section===name?'page':undefined} onClick={()=>navigate(name)}><span>{['◫','▤','◇','≡','▧','↗','⚙','◎'][i]}</span>{name}{section===name&&<i>·</i>}</button>)}</nav><div className="cms-side-note"><span className="cms-dot"/> 原型演示模式<p>無真實賬號、資料庫或客戶資料</p></div></aside>
 <main className="cms-main"><header className="cms-top"><span>網站管理 <em>/</em> {section}</span><a href="/" target="_blank" rel="noreferrer">檢視現有前臺 ↗</a><span className="cms-avatar">LF</span></header><div className="cms-banner">設計原型 · 示例內容，僅本次會話有效，重新整理重置；不會修改線上網站。請勿填寫真實客戶資訊。</div><div className="cms-content"><div className="cms-heading"><div><small>CONTENT WORKSPACE</small><h1>{section}</h1><p>{['首頁管理','產品管理','文章管理'].includes(section)?'編輯內容，實時預覽。頁面佈局與動效保持獨立。':'統一管理原料網站的內容與日常工作。'}</p></div>{['產品管理','文章管理'].includes(section)&&<button className="cms-primary" onClick={add}>＋ 新建{section==='文章管理'?'文章':'產品'}</button>}</div>
 {['首頁管理','產品管理','文章管理'].includes(section)?<><div className="cms-editor"><section className="cms-list"><h2>{section==='首頁管理'?'頁面區塊':'內容列表'} <small>{filtered.length}</small></h2><input aria-label="搜尋內容" placeholder="搜尋標題或型號…" value={search} onChange={e=>setSearch(e.target.value)}/>{filtered.map((item,i)=><button className={selected===item.id?'chosen':''} key={item.id} onClick={()=>select(item)}><img src={item.image} alt=""/><span><small>{String(i+1).padStart(2,'0')} / {item.status}</small><strong>{item.title}</strong></span><span>›</span></button>)}{!filtered.length&&<p>沒有找到匹配內容。</p>}</section><section className="cms-form"><div className="cms-tabs">{['內容編輯','展示設定'].map(t=><button aria-pressed={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='內容編輯'?<><label>標題 / 產品型號<input maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>{section==='產品管理'?'引數與產品介紹':section==='文章管理'?'文章正文（純文字原型）':'說明文字'}<textarea rows={8} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><label>展示圖片<img className="cms-upload-preview" src={draft.image} alt="當前展示圖片"/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/><small>JPG / PNG / WebP，最大 5 MB。建議使用清晰的橫向圖片。</small></label></>:<><label>展示狀態<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>展示</option><option>草稿</option><option>隱藏</option></select></label><p className="cms-help">這裡只演示內容狀態。正式版本將連線稽核與釋出服務，當前狀態不會改變公開頁面。</p><h3>正式版本規劃</h3><p>排序、SEO、多語言和歷史版本恢復將在資料庫接入階段實現。</p></>}</section><aside className="cms-preview"><div><span className="cms-dot"/> 實時內容預覽 <small>非完整前臺頁面</small></div><article><img src={draft.image} alt={draft.title}/><small>LEAD FAIR / {draft.status}</small><h2>{draft.title||'未填寫標題'}</h2><p>{draft.text||'在左側填寫內容，此處將實時顯示。'}</p></article><p className="cms-help">此處預覽圖片與文字，不模擬前臺全部佈局和動效。</p></aside></div><footer className="cms-actions"><span>{dirty?'● 有未儲存的修改':'✓ 當前內容已同步至演示會話'}</span><button onClick={()=>{if(saved&&leave())setDraft({...saved});}}>撤銷未儲存修改</button><button className="cms-primary" onClick={save}>儲存演示草稿</button><button disabled title="需要連線資料庫與釋出服務">釋出到網站 ↗</button></footer></>:
 section==='工作臺'?<><div className="cms-stats">{[['內容區塊',items.filter(x=>x.group==='首頁管理').length],['產品型號',items.filter(x=>x.group==='產品管理').length],['技術文章',items.filter(x=>x.group==='文章管理').length]].map(([label,n])=><button key={label} onClick={()=>navigate(label==='內容區塊'?'首頁管理':label==='產品型號'?'產品管理':'文章管理')}><span>{label}</span><b>{n}</b><small>檢視並編輯 ↗</small></button>)}</div><section className="cms-panel"><h2>本次會話的修改</h2>{history.length?history.map((h,i)=><p key={i}>已儲存演示草稿 · {h}</p>):<p>還沒有儲存記錄。從首頁、產品或文章開始編輯。</p>}</section></>:
 section==='素材與資料'?<section className="cms-panel"><h2>當前內容使用的圖片</h2><p>在對應內容的編輯頁可替換圖片。正式檔案庫與 PDF 上傳尚未接入。</p><div className="cms-assets">{items.map(item=><button key={item.id} onClick={()=>{if(!leave())return;setSection(item.group);setSelected(item.id);setDraft({...item});}}><img src={item.image} alt=""/><strong>{item.title}</strong><small>編輯使用位置 ↗</small></button>)}</div></section>:
 <section className="cms-panel cms-empty"><span>{section==='客戶詢盤'?'↗':section==='賬號與許可權'?'◎':'⚙'}</span><h2>{section==='客戶詢盤'?'尚未連線詢盤服務':section==='賬號與許可權'?'賬號與許可權待接入':'正式網站設定待接入'}</h2><p>{section==='客戶詢盤'?'正式版將在這裡顯示新詢盤、處理狀態和內部備註。當前沒有真實客戶資料。':section==='賬號與許可權'?'計劃支援管理員與內容編輯兩類許可權。本原型沒有登入驗證，不可作為正式後臺公開使用。':'計劃統一管理聯絡資訊、語言、SEO 和通知郵箱。當前不會修改這些正式設定。'}</p></section>}
 <p role="status" className="cms-notice">{notice}</p></div></main></div>;
}
