"use client";
import { useEffect, useState } from "react";
import Blog from "./Blog";
import LanguageSwitcher from "./LanguageSwitcher";
const faq=[
  {title:"可以依產品需求客製材料配方嗎？",answer:"可以。我們可依客戶產品用途、加工製程及性能需求進行 TPE 材料配方開發，並針對硬度、密度、回彈性、手感、顏色及其他物性需求進行調整。\n\n若客戶已有現行材料或產品樣品，也可提供樣品及相關物性要求，作為材料分析與配方開發的參考。"},
  {title:"如何為產品選擇合適的 TPE 材料？",answer:"我們會依產品用途、結構設計、成型方式及目標性能協助客戶進行材料選型。\n\n客戶可提供產品樣品、圖面或相關需求，包括硬度、密度、回彈性、外觀、使用環境及其他特殊物性要求，我們將依實際應用推薦合適的材料方案，必要時進一步進行客製配方開發。"},
  {title:"是否支持小批量試料與打樣？",answer:"支持。針對新材料開發及客戶前期驗證需求，我們可提供小批量試料及打樣服務，並依產品的硬度、密度、回彈性及加工需求進行配方調整。\n\n實際試料與打樣數量、費用及交期，將依材料與開發項目個別確認。"},
  {title:"客製材料開發週期通常多久？",answer:"一般材料配方的初步開發約需 2–4 週，實際時間依材料性能、硬度、密度、加工製程及最終應用要求而定。\n\n開發初期，我們會依客戶產品用途及目標性能建立材料開發方向，並針對不同應用需求評估與驗證相關物性，包括：硬度、密度、拉伸強度、斷裂伸長率、撕裂強度、回彈性、壓縮永久變形、及其他特定性能要求。\n\n針對發泡 TPE 材料，我們亦會進一步評估發泡倍率、成型密度、泡孔結構、表面品質、尺寸穩定性及成型加工性，並透過實際射出成型驗證材料與製程的匹配性。\n\n若產品涉及特殊發泡性能、耐久性或其他特定物性要求，我們會依測試結果進行配方調整、試料、成型及再驗證。因此，部分專案可能需要多輪開發，以確保材料性能與實際產品需求相符。"},
  {title:"可以依目標密度、硬度及回彈性開發發泡材料嗎？",answer:"可以。發泡 TPE 材料是我們重點開發及應用的領域之一，可依不同產品需求調整材料的硬度、密度、回彈性、手感及發泡效果。\n\n我們會同時考量材料配方與實際成型條件，透過試料及成型驗證，協助客戶取得適合產品需求的材料與製程方案。"},
  {title:"材料適用於哪些成型製程？",answer:"我們目前主要專注於 TPE 材料的射出成型與射出發泡應用，並可依產品結構、硬度、密度、回彈性及表面要求進行配方設計與製程調整。\n\n我們具備從材料配方、造粒到實際成型驗證的經驗，可協助客戶解決材料與加工製程之間的匹配問題。"},
  {title:"可提供哪些材料認證與第三方測試？",answer:"可依材料及客戶目標市場需求，提供現有相關材料資料，或配合安排第三方實驗室檢測，包括 REACH、RoHS 及其他指定化學物質測試。\n\n部分生質材料亦可提供 USDA Biobased 相關資料。實際可提供的認證、測試項目及報告，將依材料牌號、最終用途及客戶要求確認。"},
  {title:"從材料開發到量產，可以提供哪些技術協助？",answer:"我們不僅提供材料，也可參與客戶從前期選材、配方開發、試料、打樣到量產導入的過程。\n\n透過材料配方、造粒及實際成型應用經驗，我們可針對試產過程中的發泡效果、密度、硬度、回彈性及成型狀況進行分析與調整，協助客戶將材料方案導入實際產品。"}
];
export default function Home(){const[open,setOpen]=useState(0);const[msg,setMsg]=useState("");const[showTds,setShowTds]=useState(false);const toast=(t:string)=>{setMsg(t);setTimeout(()=>setMsg(""),2500)};useEffect(()=>{if(!window.matchMedia("(pointer:fine)").matches)return;const root=document.documentElement;const move=(e:PointerEvent)=>{root.style.setProperty("--mouse-x",`${e.clientX}px`);root.style.setProperty("--mouse-y",`${e.clientY}px`)};const targets=document.querySelectorAll<HTMLElement>(".material,.product-visual,.heat-test>div,.industry-list article");const handlers:Array<[HTMLElement,(e:PointerEvent)=>void,()=>void]>=[];targets.forEach(el=>{const onMove=(e:PointerEvent)=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.setProperty("--tilt-x",`${(-y*4).toFixed(2)}deg`);el.style.setProperty("--tilt-y",`${(x*5).toFixed(2)}deg`)};const onLeave=()=>{el.style.setProperty("--tilt-x","0deg");el.style.setProperty("--tilt-y","0deg")};el.addEventListener("pointermove",onMove);el.addEventListener("pointerleave",onLeave);handlers.push([el,onMove,onLeave])});window.addEventListener("pointermove",move,{passive:true});document.body.classList.add("has-pointer-fx");return()=>{window.removeEventListener("pointermove",move);handlers.forEach(([el,a,b])=>{el.removeEventListener("pointermove",a);el.removeEventListener("pointerleave",b)});document.body.classList.remove("has-pointer-fx")}},[]);return <main><div className="cursor-glow" aria-hidden="true"/><div className="cursor-dot" aria-hidden="true"/>
<header className="top shell"><a className="logo" href="#top"><i>R</i><span>原料网站<small>ADVANCED MATERIALS</small></span></a><nav><a href="#materials">材料解决方案</a><a href="#rd">定制研发</a><a href="#industries">应用行业</a><a href="#factory">工厂实力</a></nav><div className="tools"><LanguageSwitcher/><button className="contact" onClick={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}>联系工程师 ↗</button></div></header>
<section className="hero shell" id="top"><img src="/images/factory-production-line-hero.png" alt="TPE 材料生产设备与洁净车间"/><div className="shade"/><div className="hero-copy"><span className="eyebrow">MATERIALS ENGINEERED FOR TOMORROW</span><h1>创新材料，<br/>驱动产品<span>进化。</span></h1><p>面向全球品牌与制造商，提供 TPE 热塑性弹性体的研发、改性、测试与规模化生产。</p><div><a className="primary" href="#materials">探索材料方案 <b>↗</b></a><button className="ghost" onClick={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}>申请免费样品</button></div></div><div className="scroll">SCROLL TO EXPLORE ↓</div></section>
<section className="metrics shell"><div className="metric-card"><i>▦</i><div><b>46<sup>+</sup> 年</b><span>制造经验</span><p>始于 1979，专注热塑材料研发与生产</p></div></div><div className="metric-card"><i>♙</i><div><b>专业研发团队</b><span>材料工程师团队</span><p>持续创新，满足客户的性能需求</p></div></div><div className="metric-card"><i>⚙</i><div><b>OEM / ODM</b><span>定制开发</span><p>从配方到量产的一站式服务</p></div></div><div className="metric-card"><i>◎</i><div><b>30<sup>+</sup> 全球合作伙伴</b><span>服务国家和地区</span><p>长期合作的全球品牌与制造商</p></div></div></section>
<section className="intro shell" id="materials"><div className="section-title"><span>01 — APPLICATION SCENARIOS</span><h2>为性能而生的<br/>先进材料体系</h2></div><p className="lead">我们不只是供应原料，更从应用场景出发解决材料问题。每一个配方，都经过实验验证与生产验证。</p><div className="application-grid"><article className="application-card"><img src="/images/application-footwear-v2.png" alt="TPE 在运动鞋材中的应用"/><div className="application-shade"/><div className="application-copy"><small>01 / FOOTWEAR MATERIALS</small><h3>鞋材</h3><p>面向运动鞋结构的高回弹、耐磨与轻量化材料方案</p></div></article><article className="application-card"><img src="/images/application-midsole.png" alt="发泡 TPE 在运动鞋中底中的应用"/><div className="application-shade"/><div className="application-copy"><small>02 / MIDSOLE</small><h3>中底</h3><p>兼顾缓震、回弹与尺寸稳定性的发泡中底材料</p></div></article><article className="application-card"><img src="/images/application-insole.png" alt="柔软 TPE 在鞋垫中的应用"/><div className="application-shade"/><div className="application-copy"><small>03 / INSOLE</small><h3>鞋垫</h3><p>柔软贴合、舒适支撑，并保持持久回弹与细腻触感</p></div></article><article className="application-card"><img src="/images/application-protective-gear.png" alt="TPE 在运动护具中的应用"/><div className="application-shade"/><div className="application-copy"><small>04 / PROTECTIVE GEAR</small><h3>运动护具</h3><p>为护膝、护肘及腕部护具提供柔韧缓冲与耐久保护</p></div></article></div></section>
<nav className="product-index shell" aria-label="产品牌号导航"><section className="product-index-guide"><span>PRODUCT GRADES</span><strong>选择产品型号</strong><p>点击型号，查看下方产品详情 <span aria-hidden="true">↓</span></p></section><div><a href="#product">IUS-4065</a><a href="#product-lf-et78a">LF-ET78A</a><a href="#product-lf-hr53a">LF-HR53A</a><a href="#product-gte-8030">GTE-8030</a><a href="#product-gte-8075">GTE-8075</a></div></nav>
<section className="product product-lf product-switch-card shell" id="product-lf-et78a">
 <div className="product-head"><div className="product-visual"><div className="product-photo"><img src="/images/lf-et78a-product.png" alt="半透明 LF-ET78A TPE 颗粒与白色发泡性能样条"/></div><span>SHORE A 78</span><small>LF-ET78A / TRANSLUCENT</small></div><div className="product-copy"><span className="eyebrow blue">FEATURED GRADE · LF-ET78A</span><h2>LF-ET78A<br/>高分散型 TPE 弹性材料</h2><p>适用于射出、押出及发泡应用，具备高延伸、良好撕裂强度、低比重与优秀回弹特性，可兼顾应用功能与制造成本。</p><div className="specs"><div><small>硬度</small><b>Shore A 78</b></div><div><small>熔融指数</small><b>2 g/10min</b></div><div><small>比重</small><b>0.87</b></div><div><small>延伸率</small><b>570%</b></div><div><small>撕裂强度</small><b>62 kgf/cm</b></div><div><small>熔点</small><b>69°C</b></div></div><button onClick={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}>咨询技术参数 ↗</button><button className="outline" onClick={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}>获取样品</button></div></div>
 <div className="lf-story"><div><span className="detail-label">APPLICATION REQUIREMENTS</span><h3>弹性发泡材料的真实应用需求</h3><ul className="lf-needs"><li>兼具高强韧与耐用性</li><li>满足轻量化与防震表现</li><li>材料性能稳定、批次一致</li><li>保持良好硬度与尺寸稳定</li><li>适用于射出、押出及压延加工</li></ul></div><div><span className="detail-label">VALUE OF LF-ET78A</span><h3>从材料性能，转化为产品价值</h3><div className="lf-value-grid">{[["01","高延伸","提升制品耐用度"],["02","高撕裂强度","降低破损风险"],["03","轻量低密度","有利产品减重"],["04","良好回弹","提升使用舒适感"],["05","加工适应性","适配多种成型方式"]].map(x=><article className="lf-value-card" key={x[0]}><b>{x[0]}</b><h4>{x[1]}</h4><p>{x[2]}</p></article>)}</div></div></div>
 <div className="lf-data"><div><span className="detail-label">MATERIAL COA / BASIC PROPERTIES</span><h3>原料基本特性</h3><div className="table-wrap"><table><thead><tr><th>项目</th><th>测试方法</th><th>数值</th></tr></thead><tbody>{[["外观","N/A","颗粒"],["颜色","N/A","半透明"],["硬度","ASTM D2240","Shore A 78"],["熔融指数","ASTM D1238","2 g/10min"],["比重","ASTM D792","0.87"],["拉力","ASTM D412","85 kgf/cm²"],["延伸率","ASTM D412","570%"],["撕裂强度","ASTM D624","62 kgf/cm"],["熔点","DSC","69°C"]].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></div><div><span className="detail-label">PROPERTIES AFTER FOAMING</span><h3>发泡后物性</h3><div className="table-wrap"><table><thead><tr><th>项目</th><th>测试方法</th><th>测试结果</th></tr></thead><tbody>{[["硬度 Asker C","ASTM D2240","50"],["密度","ASTM D792","0.1919"],["拉力 N/mm²","ASTM D638","4.6"],["延伸率","ASTM D638","446%"],["撕裂强度 N/mm","ASTM D624","5.65"],["回弹度","ASTM D3574","62"],["收缩率","60°C / 120 分钟","1%"],["压缩变形","35°C / 6 小时","20%"],["倍率 E/R","—","190%"],["压缩比 CR","—","1.9"]].map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></div></div>
 <div className="lf-advantages">{[["01","高回弹"],["02","轻量低密度"],["03","高柔韧性"],["04","尺寸稳定"],["05","加工通用性"],["06","适合鞋材与发泡制品"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div>
</section>
<ProductGrade id="product-lf-hr53a" name="LF-HR53A" title="高分散型 TPE 弹性材料" description="高分散微细型热塑性体化合，适用于射出、押出及发泡应用；具备高延伸、良好耐磨强度、低比重与良好回弹弹性。" specs={[["硬度","Shore A 53"],["熔融指数","0.32 g/10min"],["比重","0.89"],["拉力","37.3 kgf/cm²"],["延伸率","360%"],["撕裂强度","38 kgf/cm"]]} needs={["优异的高反弹回弹性能","兼顾低密度与耐用性","耐比重与轻量化","低比重、抗冲击与耐磨性","适用于射出、押出与发泡加工"]} values={["高反弹，提供卓越缓冲体验","良好耐磨强度，提升耐用性","低比重，有利产品轻量化","高延伸特性，适合发泡应用","加工适用性佳，适用多元制程"]} raw={[["外观","N/A","白色"],["颜色","N/A","半透明"],["硬度","ASTM D2240","Shore A 53"],["熔融指数","ASTM D1238","0.32 g/10min"],["比重","ASTM D792","0.89"],["拉力","ASTM D412","37.3 kgf/cm²"],["延伸率","ASTM D412","360%"],["撕裂强度","ASTM D624","38 kgf/cm"],["熔点","DSC","69°C"]]} foamed={[["硬度 Asker C","ASTM D2240","34"],["比重","ASTM D792","0.1338"],["拉力","ASTM D638","15.3 kgf/cm²"],["延伸率","ASTM D638","182.1%"],["撕裂强度","ASTM D624","71.3 kgf/cm"],["吸能率","70°C / 120 分钟","3.4%"],["压缩率","50°C / 6 小时","21%"],["压缩倍率 LFR","—","215"],["压缩比 CR","—","2.28"]]} faq={[["适合哪些加工方式？","适用于射出、押出与发泡成型。"],["主要用途？","适合鞋材、鞋垫、良好舒适体验、鞋垫与发泡缓冲用途。"],["材料特性？","高延伸、良好耐磨强度、低比重与良好回弹性。"]]} onInquiry={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}/>
<ProductGrade id="product-gte-8030" name="GTE-8030" title="生质高反弹 TPE 弹性材料" description="生质含量 30%，与 EVA、POE 具有良好相容性；兼具高弹性与高反弹，适用于发泡鞋材、鞋中底、鞋垫及各类缓冲材料。" specs={[["生质含量","30%"],["硬度","Shore A 72"],["熔融指数","4.7 g/10min"],["密度","0.91 g/cm³"],["反弹率","51%"],["延伸率","665%"]]} needs={["回弹性不足，脚感偏硬","耐用性不足，使用寿命较短","生质含量低，不符合永续趋势","发泡孔结构不稳定，影响性能","加工性不佳，限制设计应用"]} values={["高反弹，提供优异脚感与舒适回馈","高韧性，提升产品耐用性","生质含量 30%，符合永续发展趋势","发泡稳定，孔结构均匀细腻","加工适用性佳，适用多元制程"]} raw={[["外观","N/A","Pellets"],["颜色","N/A","Translucent"],["硬度","ASTM D2240","Shore A 72"],["熔融指数","ASTM D1238","4.7 g/10min（2.16kg@190°C）"],["密度","ASTM D792","0.91 g/cm³"],["拉伸强度","ASTM D638","88 kgf/cm²"],["延伸率","ASTM D638","665%"],["撕裂强度","ASTM D624","56 kgf/cm"],["生质含量","ASTM D6866","30%"],["熔点","DSC","85°C"]]} foamed={[["硬度","ASTM D2240","Asker C 50"],["密度","ASTM D792","0.2152 g/cm³"],["拉伸强度","ASTM D638","18 kgf/cm²"],["延伸率","ASTM D638","293%"],["撕裂强度","ASTM D624","8 kgf/cm"],["落球反弹率","ASTM D2632","51%"],["压缩永久变形","ASTM D395","52%"],["收缩","ASTM D955","0.5%"],["倍率 E/R","—","160%"]]} faq={[["适合哪些加工方式？","适用于射出、发泡、压缩成型及热压等多种加工方式。"],["生质含量是多少？","生质含量为 30%，采用可再生原料。"],["产品特点？","高反弹、柔软弹性、耐用性佳、发泡稳定且加工适用性佳。"]]} onInquiry={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}/>
<section className="product product-coming product-switch-card shell" id="product-gte-8075"><div className="product-head"><div className="product-visual"><div className="product-photo"><img src="/images/lf-et78a-product.png" alt="GTE-8075 材料产品预览"/></div><span>PRODUCT GRADE</span><small>GTE-8075</small></div><div className="product-copy"><span className="eyebrow blue">PRODUCT GRADE · GTE-8075</span><h2>GTE-8075<br/>产品资料整理中</h2><p>该牌号的完整参数与应用资料将在后续补充，您可以先联系材料工程师获取选材建议与样品支持。</p><button onClick={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}>咨询产品 ↗</button></div></div></section>
<section className="product product-switch-card shell" id="product">
 <div className="product-head"><div className="product-visual"><div className="product-photo"><img src="/images/ius-4065-white-pellets-v4-scattered.png" alt="自然散落的白色半透明 IUS-4065 TPE 颗粒与黑色性能样片"/></div><span>SHORE A 40</span><small>IUS–4065 / NATURAL</small></div><div className="product-copy"><span className="eyebrow blue">FEATURED GRADE · IUS–4065</span><h2>IUS–4065<br/>超柔软 · 更高熔点 · 更稳定加工</h2><p>专为兼顾卓越柔软性与更高耐热性能而研发。IUS–4065 能够满足对舒适性、尺寸稳定性及制造可靠性有更高要求的产品，是高性能发泡及注塑应用的理想材料解决方案。</p><div className="specs"><div><small>硬度</small><b>Shore A 40</b></div><div><small>熔点</small><b>≈ 64°C</b></div><div><small>热收缩性</small><b>优异</b></div><div><small>尺寸稳定性</small><b>优异</b></div><div><small>加工稳定性</small><b>优异</b></div></div><button onClick={()=>setShowTds(true)}>下载技术数据表 ↓</button><button className="outline" onClick={()=>document.querySelector("#inquiry")?.scrollIntoView({behavior:"smooth"})}>获取样品</button></div></div>
 <div className="product-detail"><div className="pain-panel"><span className="detail-label">THE PROBLEM WE SOLVE</span><h3>传统低熔点材料的痛点，<br/>IUS–4065 一次系统解决</h3><p className="pain-subtitle">传统低熔点材料在加工及使用过程中常出现多种问题，而 IUS–4065 能有效解决这些痛点。</p><div className="pain-compare"><ul className="before"><strong>传统材料</strong><li>二次热收缩导致翘曲变形</li><li>耐热性不足，产品易变形</li><li>尺寸稳定性差、公差大</li><li>加工波动大、次品率高</li><li>外观不一致，影响品质</li></ul><span className="compare-arrow">→</span><ul className="after"><strong>IUS–4065</strong><li>更低热收缩，减少翘曲</li><li>更高熔点，耐热性更好</li><li>尺寸稳定，公差更可控</li><li>加工稳定，效率更高</li><li>外观一致，品质稳定</li></ul></div></div><div className="why-panel"><span className="detail-label">WHY IUS–4065</span><h3>为什么选择 IUS–4065？</h3><p>许多超柔软配方会采用 TAFMER 或 ENGAGE 系列 POE 来实现低硬度。然而，这类体系通常存在热收缩率高、易变形等问题。IUS–4065 成功兼顾超柔软硬度、更高熔点与更稳定加工性能，让产品同时拥有舒适触感与卓越制造表现。</p><div className="heat-test"><div className="fail"><small>低熔点材料<br/>DF640 / ENGAGE 8842</small><div className="sample-image warped"><i/><i/></div><b>&lt; 50°C</b><em>容易发生二次热收缩、<br/>翘曲及外观不一致</em></div><span>加工温度<br/><strong>&gt;50°C →</strong><i>层压 / 后加工温度</i></span><div className="pass"><small>IUS–4065（约 64°C）</small><div className="sample-image stable"><i/></div><b>≈ 64°C</b><em>✓ 尺寸稳定性优异<br/>✓ 产品品质一致<br/>✓ 良率更高</em></div></div></div></div>
 <div className="performance"><div><span className="detail-label">PERFORMANCE COMPARISON</span><h3>材料性能对比</h3><div className="table-wrap"><table><thead><tr><th>性能 / Property</th><th>测试标准</th><th>DF640</th><th>ENGAGE 8842</th><th>IUS–4065</th></tr></thead><tbody><tr><td>硬度 Shore A</td><td>ASTM D2240</td><td>54–56</td><td>54–56</td><td>40</td></tr><tr><td>熔点 °C</td><td>DSC</td><td>&lt; 50</td><td>&lt; 50</td><td>≈ 64</td></tr><tr><td>热收缩风险</td><td>内部测试</td><td className="bad">高</td><td className="bad">高</td><td className="good">低</td></tr><tr><td>尺寸稳定性</td><td>内部测试</td><td className="bad">低</td><td className="bad">低</td><td className="good">高</td></tr><tr><td>柔软触感</td><td>内部评估</td><td className="rating-bad">★★★★☆</td><td className="rating-bad">★★★★☆</td><td className="good">★★★★★</td></tr><tr><td>加工稳定性</td><td>内部评估</td><td className="rating-bad">★★★☆☆</td><td className="rating-bad">★★★☆☆</td><td className="good">★★★★☆</td></tr></tbody></table></div></div><div className="advantages"><span className="detail-label">PRODUCT ADVANTAGES</span><h3>五项核心优势</h3>{[["01","超柔软触感","Shore A 40，触感舒适细腻"],["02","更高熔点","约 64°C，降低二次热收缩风险"],["03","卓越尺寸稳定","减少翘曲，尺寸更可控"],["04","更高良率","加工窗口稳定，减少次品"],["05","适用高性能应用","满足更高耐热与稳定性要求"]].map(x=><div className="advantage" key={x[0]}><b>{x[0]}</b><span>{x[1]}<small>{x[2]}</small></span></div>)}</div></div>
</section>
<section className="rd service-process" id="rd"><div className="shell"><header className="process-head"><div><span>03 — CUSTOM MATERIAL SERVICE</span><h2>定制材料<br/>开发服务</h2></div><div><p>从需求沟通到批量生产交付，我们提供完整的材料定制解决方案，让每一步研发都有清晰目标与可靠验证。</p><a href="#inquiry">启动定制项目 ↗</a></div></header><div className="process-track"><article><b>01</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h12a3 3 0 0 1 3 3v5a3 3 0 0 1-3 3H9l-5 4v-4a3 3 0 0 1-2-3V8a3 3 0 0 1 2-3Z"/><path d="M7 9h7M7 12h5"/></svg></i><h3>需求沟通</h3><p>明确应用场景、目标性能、认证及交付要求</p></article><article><b>02</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m14.5 14.5 5 5M8 7v5l-2 3h8l-2-3V7"/></svg></i><h3>材料分析</h3><p>评估基材体系、加工条件与关键性能边界</p></article><article><b>03</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3h6M10 3v5l-5 9a3 3 0 0 0 2.6 4h8.8a3 3 0 0 0 2.6-4l-5-9V3"/><path d="M7 15h10M9 18h6"/></svg></i><h3>配方开发</h3><p>围绕硬度、颜色、密度与熔点进行配方设计</p></article><article><b>04</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4h8l2 2v15H6V6l2-2Z"/><path d="M9 4V2h6v2M9 11l2 2 4-4M9 17h6"/></svg></i><h3>样品测试</h3><p>完成物性、耐热、收缩与加工稳定性验证</p></article><article><b>05</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 20V9l5 3V8l5 3V5l8 4v11H3Z"/><path d="M7 16h2M12 16h2M17 16h2"/></svg></i><h3>试产验证</h3><p>通过小批试产优化工艺窗口与产品一致性</p></article><article><b>06</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 9 12 4l9 5-9 5-9-5Z"/><path d="m3 14 9 5 9-5M3 9v5M21 9v5"/></svg></i><h3>批量生产</h3><p>标准化生产、品质管控并按计划稳定交付</p></article></div></div></section>
<section className="factory shell" id="factory"><div className="factory-photo"><img src="/images/factory-capability-production.png" alt="TPE 材料混炼与生产车间"/><span>PRODUCTION / LAB / QUALITY</span></div><div className="factory-copy"><span>04 — FACTORY CAPABILITY</span><h2>研发与制造，<br/>在同一套质量体系内</h2><p>从原料检验、配方混炼到造粒与出厂检测，全流程数据化管理。让实验室性能稳定复现于每一批量产订单。</p><ul><li>双螺杆精密混炼与造粒</li><li>完整物性與耐久性能驗證</li><li>批次 COA 与全流程追溯</li><li>OEM / ODM 柔性生产</li></ul></div></section>
<section className="why-found shell"><header><span>05 — WHY FOUND FAIR</span><h2>为什么选择 Found Fair</h2><p>从研发、检测到定制与协同，我们以工程能力贯穿材料开发全过程，让每一个项目更快走向稳定量产。</p></header><div className="why-found-grid"><article><div><img src="/images/why-rd-team-cn.png" alt="中国材料研发工程师团队"/><b>01</b></div><h3>材料研发能力</h3><p>专业的研发团队，根据客户需求开发更优性能，满足定制化配方要求。</p></article><article><div><img src="/images/why-testing-cn.png" alt="中国材料工程师进行实验检测"/><b>02</b></div><h3>先进实验检测能力</h3><p>完整的检测设备与测试流程，精准验证材料性能并缩短研发周期。</p></article><article><div><img src="/images/why-formulation-cn.png" alt="中国配方工程师开发定制材料"/><b>03</b></div><h3>定制配方开发能力</h3><p>从配方设计、样品测试到量产交付，提供一站式定制开发服务。</p></article><article><div><img src="/images/why-collaboration-cn.png" alt="中国工程师与客户团队协同开发"/><b>04</b></div><h3>工程师协同开发</h3><p>工程师直接对接客户技术团队，共同解决真实产品中的材料应用问题。</p></article></div></section>
<Blog />
<section className="faq shell"><div><span>07 — FAQ</span><h2>合作前，您可能<br/>想了解这些</h2></div><div>{faq.map((q,i)=><button onClick={()=>setOpen(open===i?-1:i)} key={q.title}><b>{String(i+1).padStart(2,"0")}</b><span>{q.title}{open===i&&<small>{q.answer.split("\n\n").map((paragraph,j)=><span className="faq-answer-paragraph" key={j}>{paragraph}</span>)}</small>}</span><i>{open===i?"−":"+"}</i></button>)}</div></section>
<section className="cta" id="contact"><div className="shell inquiry-wrap"><div className="inquiry-copy"><span>READY TO BUILD WHAT'S NEXT?</span><h2>让下一款产品，<br/>从更好的材料开始。</h2><p>留下您的项目需求与联系方式，材料工程师将在 24 小时内回复，并提供适配建议与样品方案。</p><div className="reply-note"><b>24h</b><small>工程师响应</small></div></div><form id="inquiry" className="inquiry-form" onSubmit={(e)=>{e.preventDefault();toast("需求已提交，我们将在 24 小时内联系您");e.currentTarget.reset()}}><div className="field-row"><label>您的姓名<input name="name" required placeholder="请输入姓名"/></label><label>公司名称<input name="company" required placeholder="请输入公司名称"/></label></div><div className="field-row"><label>工作邮箱<input name="email" required type="email" placeholder="name@company.com"/></label><label>联系电话<input name="phone" required type="tel" placeholder="国家代码 + 电话号码"/></label></div><div className="field-row"><label>目标材料<select name="material" defaultValue="IUS-4065"><option>IUS-4065</option><option>阻燃 TPE</option><option>生物基 TPE</option><option>其他定制材料</option></select></label><label>预计用量<input name="volume" placeholder="例如：5 吨 / 月"/></label></div><label>项目需求<textarea name="message" rows={4} placeholder="请描述应用场景、硬度、颜色、认证或交付要求"/></label><label className="consent"><input type="checkbox" required/> 我同意材料工程师就本次项目需求与我联系</label><button type="submit">提交样品申请 <b>↗</b></button></form></div></section>
{showTds&&<div className="tds-modal" role="dialog" aria-modal="true" aria-label="IUS-4065 技术数据表预览" onClick={()=>setShowTds(false)}><div className="tds-card" onClick={(e)=>e.stopPropagation()}><header><div><small>TECHNICAL DATA SHEET</small><h3>IUS–4065 技术数据表</h3><p>产品性能、材料对比与应用优势预览</p></div><button type="button" aria-label="关闭预览" onClick={()=>setShowTds(false)}>×</button></header><div className="tds-preview"><img src="/images/IUS-4065-technical-datasheet.png" alt="IUS-4065 技术数据表"/></div><footer><span>PNG · 1536 × 1024</span><a href="/images/IUS-4065-technical-datasheet.png" download="IUS-4065-Technical-Datasheet.png">下载数据表 ↓</a></footer></div></div>}<footer className="footer shell"><a className="logo" href="#top"><i>R</i><span>原料网站<small>ADVANCED MATERIALS</small></span></a><p>Advanced thermoplastic material solutions for global manufacturing.</p><div><a href="#materials">Materials</a><a href="#rd">R&D</a><a href="#factory">Factory</a><a href="#contact">Contact</a></div><small>© 2026 原料网站. All rights reserved.</small></footer>{msg&&<div className="toast">✓ {msg}</div>}
</main>}

function ProductGrade({id,name,title,description,specs,needs,values,raw,foamed,faq,onInquiry}:{id:string;name:string;title:string;description:string;specs:string[][];needs:string[];values:string[];raw:string[][];foamed:string[][];faq:string[][];onInquiry:()=>void}) {
 return <section className="product product-lf product-switch-card shell" id={id}><div className="product-head"><div className="product-visual"><div className="product-photo"><img src="/images/lf-et78a-product.png" alt={`${name} TPE 颗粒与发泡样条`}/></div><span>{specs[0][1]}</span><small>{name} / PRODUCT GRADE</small></div><div className="product-copy"><span className="eyebrow blue">FEATURED GRADE · {name}</span><h2>{name}<br/>{title}</h2><p>{description}</p><div className="specs">{specs.map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><button onClick={onInquiry}>咨询技术参数 ↗</button><button className="outline" onClick={onInquiry}>获取样品</button></div></div><div className="lf-story"><div><span className="detail-label">APPLICATION REQUIREMENTS</span><h3>常见材料需求</h3><ul className="lf-needs">{needs.map(x=><li key={x}>{x}</li>)}</ul></div><div><span className="detail-label">{`VALUE OF ${name}`}</span><h3>{name} 带来的价值</h3><div className="lf-value-grid">{values.map((x,i)=><article className="lf-value-card" key={x}><b>{String(i+1).padStart(2,"0")}</b><h4>{x}</h4></article>)}</div></div></div><div className="lf-data"><ProductTable title="原料基本特性" rows={raw}/><ProductTable title="发泡后物性" rows={foamed}/></div><div className="lf-faq"><span className="detail-label">FAQ</span><h3>常见问题</h3>{faq.map((x,i)=><article key={x[0]}><b>Q{String(i+1).padStart(2,"0")}</b><h4>{x[0]}</h4><p>{x[1]}</p></article>)}</div></section>
}
function ProductTable({title,rows}:{title:string;rows:string[][]}) { return <div><span className="detail-label">TECHNICAL PROPERTIES</span><h3>{title}</h3><div className="table-wrap"><table><thead><tr><th>项目</th><th>测试方法</th><th>数值</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></div> }
