"use client";
import { useEffect, useState } from "react";
import Blog from "./Blog";
import LanguageSwitcher from "./LanguageSwitcher";
import SiteHeader from "./SiteHeader";
import SiteFooter from "./SiteFooter";
import HomeProductSection from "./HomeProductSection";
const faq=[
  {title:"可以依產品需求客製材料配方嗎？",answer:"可以。我們可依客戶產品用途、加工製程及效能需求進行 TPE 材料配方開發，並針對硬度、密度、回彈性、手感、顏色及其他物性需求進行調整。\n\n若客戶已有現行材料或產品樣品，也可提供樣品及相關物性要求，作為材料分析與配方開發的參考。"},
  {title:"如何為產品選擇合適的 TPE 材料？",answer:"我們會依產品用途、結構設計、成型方式及目標效能協助客戶進行材料選型。\n\n客戶可提供產品樣品、圖面或相關需求，包括硬度、密度、回彈性、外觀、使用環境及其他特殊物性要求，我們將依實際應用推薦合適的材料方案，必要時進一步進行客製配方開發。"},
  {title:"是否支援小批次試料與打樣？",answer:"支援。針對新材料開發及客戶前期驗證需求，我們可提供小批次試料及打樣服務，並依產品的硬度、密度、回彈性及加工需求進行配方調整。\n\n實際試料與打樣數量、費用及交期，將依材料與開發專案個別確認。"},
  {title:"客製材料開發週期通常多久？",answer:"一般材料配方的初步開發約需 2–4 週，實際時間依材料效能、硬度、密度、加工製程及最終應用要求而定。\n\n開發初期，我們會依客戶產品用途及目標效能建立材料開發方向，並針對不同應用需求評估與驗證相關物性，包括：硬度、密度、拉伸強度、斷裂伸長率、撕裂強度、回彈性、壓縮永久變形、及其他特定效能要求。\n\n針對發泡 TPE 材料，我們亦會進一步評估發泡倍率、成型密度、泡孔結構、表面品質、尺寸穩定性及成型加工性，並透過實際射出成型驗證材料與製程的匹配性。\n\n若產品涉及特殊發泡效能、耐久性或其他特定物性要求，我們會依測試結果進行配方調整、試料、成型及再驗證。因此，部分專案可能需要多輪開發，以確保材料效能與實際產品需求相符。"},
  {title:"可以依目標密度、硬度及回彈性開發發泡材料嗎？",answer:"可以。發泡 TPE 材料是我們重點開發及應用的領域之一，可依不同產品需求調整材料的硬度、密度、回彈性、手感及發泡效果。\n\n我們會同時考量材料配方與實際成型條件，透過試料及成型驗證，協助客戶取得適合產品需求的材料與製程方案。"},
  {title:"材料適用於哪些成型製程？",answer:"我們目前主要專注於 TPE 材料的射出成型與射出發泡應用，並可依產品結構、硬度、密度、回彈性及表面要求進行配方設計與製程調整。\n\n我們具備從材料配方、造粒到實際成型驗證的經驗，可協助客戶解決材料與加工製程之間的匹配問題。"},
  {title:"可提供哪些材料認證與第三方測試？",answer:"可依材料及客戶目標市場需求，提供現有相關材料資料，或配合安排第三方實驗室檢測，包括 REACH、RoHS 及其他指定化學物質測試。\n\n部分生質材料亦可提供 USDA Biobased 相關資料。實際可提供的認證、測試專案及報告，將依材料牌號、最終用途及客戶要求確認。"},
  {title:"從材料開發到量產，可以提供哪些技術協助？",answer:"我們不僅提供材料，也可參與客戶從前期選材、配方開發、試料、打樣到量產匯入的過程。\n\n透過材料配方、造粒及實際成型應用經驗，我們可針對試產過程中的發泡效果、密度、硬度、回彈性及成型狀況進行分析與調整，協助客戶將材料方案匯入實際產品。"}
];
export default function Home(){const[open,setOpen]=useState(0);const[msg,setMsg]=useState("");const toast=(t:string)=>{setMsg(t);setTimeout(()=>setMsg(""),2500)};useEffect(()=>{if(!window.matchMedia("(pointer:fine)").matches)return;const root=document.documentElement;const move=(e:PointerEvent)=>{root.style.setProperty("--mouse-x",`${e.clientX}px`);root.style.setProperty("--mouse-y",`${e.clientY}px`)};const targets=document.querySelectorAll<HTMLElement>(".material,.product-visual,.heat-test>div,.industry-list article");const handlers:Array<[HTMLElement,(e:PointerEvent)=>void,()=>void]>=[];targets.forEach(el=>{const onMove=(e:PointerEvent)=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.setProperty("--tilt-x",`${(-y*4).toFixed(2)}deg`);el.style.setProperty("--tilt-y",`${(x*5).toFixed(2)}deg`)};const onLeave=()=>{el.style.setProperty("--tilt-x","0deg");el.style.setProperty("--tilt-y","0deg")};el.addEventListener("pointermove",onMove);el.addEventListener("pointerleave",onLeave);handlers.push([el,onMove,onLeave])});window.addEventListener("pointermove",move,{passive:true});document.body.classList.add("has-pointer-fx");return()=>{window.removeEventListener("pointermove",move);handlers.forEach(([el,a,b])=>{el.removeEventListener("pointermove",a);el.removeEventListener("pointerleave",b)});document.body.classList.remove("has-pointer-fx")}},[]);return <main><div className="cursor-glow" aria-hidden="true"/><div className="cursor-dot" aria-hidden="true"/>
<SiteHeader/>
<section className="hero shell" id="top"><img src="/images/factory-production-line-hero-fast.jpg" alt="TPE 材料生產裝置與潔淨車間"/><div className="shade"/><div className="hero-copy"><span className="eyebrow">MATERIALS ENGINEERED FOR TOMORROW</span><h1>創新材料，<br/>驅動產品<span>進化。</span></h1><p>面向全球品牌與製造商，提供 TPE 熱塑性彈性體的研發、改性、測試與規模化生產。</p><div><a className="primary" href="#materials">探索材料方案 <b>↗</b></a><button className="ghost" onClick={()=>window.location.href="/contact/#inquiry"}>申請免費樣品</button></div></div><div className="scroll">SCROLL TO EXPLORE ↓</div></section>
<section className="metrics shell"><div className="metric-card"><i>▦</i><div><b>46<sup>+</sup> 年</b><span>製造經驗</span><p>始於 1979，專注熱塑材料研發與生產</p></div></div><div className="metric-card"><i>♙</i><div><b>專業研發團隊</b><span>材料工程師團隊</span><p>持續創新，滿足客戶的效能需求</p></div></div><div className="metric-card"><i>⚙</i><div><b>OEM / ODM</b><span>定製開發</span><p>從配方到量產的一站式服務</p></div></div><div className="metric-card"><i>◎</i><div><b>30<sup>+</sup> 全球合作伙伴</b><span>服務國家和地區</span><p>長期合作的全球品牌與製造商</p></div></div></section>
<section className="intro shell" id="materials"><div className="section-title"><span>01 — APPLICATION SCENARIOS</span><h2>為效能而生的<br/>先進材料體系</h2></div><p className="lead">我們不只是供應原料，更從應用場景出發解決材料問題。每一個配方，都經過實驗驗證與生產驗證。</p><div className="application-grid"><article className="application-card"><img src="/images/application-footwear-v2-fast.jpg" alt="TPE 在運動鞋材中的應用"/><div className="application-shade"/><div className="application-copy"><small>01 / FOOTWEAR MATERIALS</small><h3>鞋材</h3><p>面向運動鞋結構的高回彈、耐磨與輕量化材料方案</p></div></article><article className="application-card"><img src="/images/application-midsole-fast.jpg" alt="發泡 TPE 在運動鞋中底中的應用"/><div className="application-shade"/><div className="application-copy"><small>02 / MIDSOLE</small><h3>中底</h3><p>兼顧緩震、回彈與尺寸穩定性的發泡中底材料</p></div></article><article className="application-card"><img src="/images/application-insole-fast.jpg" alt="柔軟 TPE 在鞋墊中的應用"/><div className="application-shade"/><div className="application-copy"><small>03 / INSOLE</small><h3>鞋墊</h3><p>柔軟貼合、舒適支撐，並保持持久回彈與細膩觸感</p></div></article><article className="application-card"><img src="/images/application-protective-gear-fast.jpg" alt="TPE 在運動護具中的應用"/><div className="application-shade"/><div className="application-copy"><small>04 / PROTECTIVE GEAR</small><h3>運動護具</h3><p>為護膝、護肘及腕部護具提供柔韌緩衝與耐久保護</p></div></article></div></section>
<HomeProductSection/>
<section className="rd service-process" id="rd"><div className="shell"><header className="process-head"><div><span>03 — CUSTOM MATERIAL SERVICE</span><h2>定製材料<br/>開發服務</h2></div><div><p>從需求溝通到批次生產交付，我們提供完整的材料定製解決方案，讓每一步研發都有清晰目標與可靠驗證。</p><a href="#inquiry">啟動定製專案 ↗</a></div></header><div className="process-track"><article><b>01</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h12a3 3 0 0 1 3 3v5a3 3 0 0 1-3 3H9l-5 4v-4a3 3 0 0 1-2-3V8a3 3 0 0 1 2-3Z"/><path d="M7 9h7M7 12h5"/></svg></i><h3>需求溝通</h3><p>明確應用場景、目標效能、認證及交付要求</p></article><article><b>02</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m14.5 14.5 5 5M8 7v5l-2 3h8l-2-3V7"/></svg></i><h3>材料分析</h3><p>評估基材體系、加工條件與關鍵效能邊界</p></article><article><b>03</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3h6M10 3v5l-5 9a3 3 0 0 0 2.6 4h8.8a3 3 0 0 0 2.6-4l-5-9V3"/><path d="M7 15h10M9 18h6"/></svg></i><h3>配方開發</h3><p>圍繞硬度、顏色、密度與熔點進行配方設計</p></article><article><b>04</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 4h8l2 2v15H6V6l2-2Z"/><path d="M9 4V2h6v2M9 11l2 2 4-4M9 17h6"/></svg></i><h3>樣品測試</h3><p>完成物性、耐熱、收縮與加工穩定性驗證</p></article><article><b>05</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 20V9l5 3V8l5 3V5l8 4v11H3Z"/><path d="M7 16h2M12 16h2M17 16h2"/></svg></i><h3>試產驗證</h3><p>透過小批試產最佳化工藝視窗與產品一致性</p></article><article><b>06</b><i><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 9 12 4l9 5-9 5-9-5Z"/><path d="m3 14 9 5 9-5M3 9v5M21 9v5"/></svg></i><h3>批次生產</h3><p>標準化生產、品質管控並按計劃穩定交付</p></article></div></div></section>
<section className="factory shell" id="factory"><div className="factory-photo"><img src="/images/factory-capability-production-fast.jpg" alt="TPE 材料混煉與生產車間"/><span>PRODUCTION / LAB / QUALITY</span></div><div className="factory-copy"><span>04 — FACTORY CAPABILITY</span><h2>研發與製造，<br/>在同一套質量體系內</h2><p>從原料檢驗、配方混煉到造粒與出廠檢測，全流程資料化管理。讓實驗室效能穩定復現於每一批次產訂單。</p><ul><li>雙螺桿精密混煉與造粒</li><li>完整物性與耐久效能驗證</li><li>批次 COA 與全流程追溯</li><li>OEM / ODM 柔性生產</li></ul></div></section>
<section className="why-found shell"><header><span>05 — WHY FOUND FAIR</span><h2>為什麼選擇 Found Fair</h2><p>從研發、檢測到定製與協同，我們以工程能力貫穿材料開發全過程，讓每一個專案更快走向穩定量產。</p></header><div className="why-found-grid"><article><div><img src="/images/why-rd-team-cn-fast.jpg" alt="中國材料研發工程師團隊"/><b>01</b></div><h3>材料研發能力</h3><p>專業的研發團隊，根據客戶需求開發更優效能，滿足定製化配方要求。</p></article><article><div><img src="/images/why-testing-cn-fast.jpg" alt="中國材料工程師進行實驗檢測"/><b>02</b></div><h3>先進實驗檢測能力</h3><p>完整的檢測裝置與測試流程，精準驗證材料效能並縮短研發週期。</p></article><article><div><img src="/images/why-formulation-cn-fast.jpg" alt="中國配方工程師開發定製材料"/><b>03</b></div><h3>定製配方開發能力</h3><p>從配方設計、樣品測試到量產交付，提供一站式定製開發服務。</p></article><article><div><img src="/images/why-collaboration-cn-fast.jpg" alt="中國工程師與客戶團隊協同開發"/><b>04</b></div><h3>工程師協同開發</h3><p>工程師直接對接客戶技術團隊，共同解決真實產品中的材料應用問題。</p></article></div></section>
<Blog />
<section className="faq shell"><div><span>07 — FAQ</span><h2>合作前，您可能<br/>想了解這些</h2></div><div>{faq.map((q,i)=><button onClick={()=>setOpen(open===i?-1:i)} key={q.title}><b>{String(i+1).padStart(2,"0")}</b><span>{q.title}{open===i&&<small>{q.answer.split("\n\n").map((paragraph,j)=><span className="faq-answer-paragraph" key={j}>{paragraph}</span>)}</small>}</span><i>{open===i?"−":"+"}</i></button>)}</div></section>
<section className="cta" id="contact"><div className="shell inquiry-wrap"><div className="inquiry-copy"><span>READY TO BUILD WHAT'S NEXT?</span><h2>讓下一款產品，<br/>從更好的材料開始。</h2><p>留下您的專案需求與聯絡方式，材料工程師將在 24 小時內回覆，並提供適配建議與樣品方案。</p><div className="reply-note"><b>24h</b><small>工程師響應</small></div></div><form id="inquiry" className="inquiry-form" onSubmit={(e)=>{e.preventDefault();toast("需求已提交，我們將在 24 小時內聯絡您");e.currentTarget.reset()}}><div className="field-row"><label>您的姓名<input name="name" required placeholder="請輸入姓名"/></label><label>公司名稱<input name="company" required placeholder="請輸入公司名稱"/></label></div><div className="field-row"><label>工作郵箱<input name="email" required type="email" placeholder="name@company.com"/></label><label>聯絡電話<input name="phone" required type="tel" placeholder="國家程式碼 + 電話號碼"/></label></div><div className="field-row"><label>目標材料<select name="material" defaultValue="IUS-4065"><option>IUS-4065</option><option>阻燃 TPE</option><option>生物基 TPE</option><option>其他定製材料</option></select></label><label>預計用量<input name="volume" placeholder="例如：5 噸 / 月"/></label></div><label>專案需求<textarea name="message" rows={4} placeholder="請描述應用場景、硬度、顏色、認證或交付要求"/></label><label className="consent"><input type="checkbox" required/> 我同意材料工程師就本次專案需求與我聯絡</label><button type="submit">提交樣品申請 <b>↗</b></button></form></div></section>
<SiteFooter/>{msg&&<div className="toast">✓ {msg}</div>}
</main>}
