"use client";
import { useEffect, useState } from "react";
const industries=[["01","鞋材与运动","高回弹 · 耐磨 · 轻量化"],["02","汽车与交通","耐候 · 阻燃 · 低气味"],["03","消费电子","柔触 · 抗污 · 低 VOC"],["04","工业部件","耐热 · 密封 · 高强度"]];
const faq=["是否支持小批量打样？","可提供哪些材料认证？","定制开发周期通常多久？","产品是否符合 REACH / RoHS？"];
export default function Home(){const[open,setOpen]=useState(0);const[msg,setMsg]=useState("");const toast=(t:string)=>{setMsg(t);setTimeout(()=>setMsg(""),2500)};useEffect(()=>{if(!window.matchMedia("(pointer:fine)").matches)return;const root=document.documentElement;const move=(e:PointerEvent)=>{root.style.setProperty("--mouse-x",`${e.clientX}px`);root.style.setProperty("--mouse-y",`${e.clientY}px`)};const targets=document.querySelectorAll<HTMLElement>(".material,.product-visual,.heat-test>div,.industry-list article");const handlers:Array<[HTMLElement,(e:PointerEvent)=>void,()=>void]>=[];targets.forEach(el=>{const onMove=(e:PointerEvent)=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.setProperty("--tilt-x",`${(-y*4).toFixed(2)}deg`);el.style.setProperty("--tilt-y",`${(x*5).toFixed(2)}deg`)};const onLeave=()=>{el.style.setProperty("--tilt-x","0deg");el.style.setProperty("--tilt-y","0deg")};el.addEventListener("pointermove",onMove);el.addEventListener("pointerleave",onLeave);handlers.push([el,onMove,onLeave])});window.addEventListener("pointermove",move,{passive:true});document.body.classList.add("has-pointer-fx");return()=>{window.removeEventListener("pointermove",move);handlers.forEach(([el,a,b])=>{el.removeEventListener("pointermove",a);el.removeEventListener("pointerleave",b)});document.body.classList.remove("has-pointer-fx")}},[]);return <main><div className="cursor-glow" aria-hidden="true"/><div className="cursor-dot" aria-hidden="true"/>
<header className="top shell"><a className="logo" href="#top"><i>R</i><span>原料网站<small>ADVANCED MATERIALS</small></span></a><nav><a href="#materials">材料解决方案</a><a href="#rd">定制研发</a><a href="#industries">应用行业</a><a href="#factory">工厂实力</a></nav><div className="tools"><button className="lang">EN⌄</button><button className="contact" onClick={()=>toast("Inquiry form is ready")}>联系工程师 ↗</button></div></header>
<section className="hero shell" id="top"><img src="https://images.prismic.io/csem/aZXvnsFoBIGEgh9h_polymer-lab-at-csem.jpg?auto=format%2Ccompress&h=1001&rect=0%2C0%2C1999%2C1334&w=1500" alt="高分子材料研发与生产车间"/><div className="shade"/><div className="hero-copy"><span className="eyebrow">MATERIALS ENGINEERED FOR TOMORROW</span><h1>创新材料，<br/>驱动产品<span>进化。</span></h1><p>面向全球品牌与制造商，提供 TPE 热塑性弹性体的研发、改性、测试与规模化生产。</p><div><a className="primary" href="#materials">探索材料方案 <b>↗</b></a><button className="ghost" onClick={()=>toast("样品申请已开启")}>申请免费样品</button></div></div><div className="hero-note"><b>01 / 03</b><span>从实验室配方<br/>到稳定量产</span></div><div className="scroll">SCROLL TO EXPLORE ↓</div></section>
<section className="metrics shell"><div><b>46<sup>+</sup></b><span>年材料制造经验</span></div><div><b>30<sup>+</sup></b><span>出口国家与地区</span></div><div><b>120<sup>+</sup></b><span>成熟材料牌号</span></div><div><b>48h</b><span>快速打样响应</span></div></section>
<section className="intro shell" id="materials"><div className="section-title"><span>01 — MATERIAL PORTFOLIO</span><h2>为性能而生的<br/>先进材料体系</h2></div><p className="lead">我们不只是供应原料，更从应用场景出发解决材料问题。每一个配方，都经过实验验证与生产验证。</p><div className="material-grid"><article className="material featured"><small>CORE MATERIAL</small><h3>超柔软 TPE</h3><p>IUS–4065</p><div className="pellets">{Array.from({length:10}).map((_,i)=><i key={i}/>)}</div><a href="#product">查看技术参数 ↗</a></article><article className="material dark"><small>HIGH PERFORMANCE</small><h3>阻燃 TPE</h3><p>面向电子电气与工业应用</p><b>V-0</b></article><article className="material light"><small>SUSTAINABLE</small><h3>生物基 TPE</h3><p>更低碳足迹的材料选择</p><b>BIO</b></article></div></section>
<section className="product shell" id="product">
 <div className="product-head"><div className="product-visual"><div className="product-photo"><img src="/images/ius-4065-product.jpg" alt="黑色 IUS-4065 TPE 颗粒产品样品"/><i className="sample-slab"/></div><span>SHORE A 40</span><small>IUS–4065 / BLACK</small></div><div className="product-copy"><span className="eyebrow blue">FEATURED GRADE · IUS–4065</span><h2>IUS–4065<br/>超柔软 · 更高熔点 · 更稳定加工</h2><p>专为兼顾卓越柔软性与更高耐热性能而研发。IUS–4065 能够满足对舒适性、尺寸稳定性及制造可靠性有更高要求的产品，是高性能发泡及注塑应用的理想材料解决方案。</p><div className="specs"><div><small>硬度</small><b>Shore A 40</b></div><div><small>熔点</small><b>≈ 64°C</b></div><div><small>热收缩</small><b>优异</b></div><div><small>尺寸稳定</small><b>优异</b></div><div><small>加工稳定</small><b>优异</b></div></div><button onClick={()=>toast("TDS 下载即将开始")}>下载技术数据表 ↓</button><button className="outline" onClick={()=>toast("样品申请已提交")}>获取样品</button></div></div>
 <div className="product-detail"><div className="pain-panel"><span className="detail-label">THE PROBLEM WE SOLVE</span><h3>传统低熔点材料的痛点，<br/>IUS–4065 一次系统解决</h3><p className="pain-subtitle">传统低熔点材料在加工及使用过程中常出现多种问题，而 IUS–4065 能有效解决这些痛点。</p><div className="pain-compare"><ul className="before"><strong>传统材料</strong><li>二次热收缩导致翘曲变形</li><li>耐热性不足，产品易变形</li><li>尺寸稳定性差、公差大</li><li>加工波动大、次品率高</li><li>外观不一致，影响品质</li></ul><span className="compare-arrow">→</span><ul className="after"><strong>IUS–4065</strong><li>更低热收缩，减少翘曲</li><li>更高熔点，耐热性更好</li><li>尺寸稳定，公差更可控</li><li>加工稳定，效率更高</li><li>外观一致，品质稳定</li></ul></div></div><div className="why-panel"><span className="detail-label">WHY IUS–4065</span><h3>为什么选择 IUS–4065？</h3><p>许多超柔软配方会采用 TAFMER 或 ENGAGE 系列 POE 来实现低硬度。然而，这类体系通常存在热收缩率高、易变形等问题。IUS–4065 成功兼顾超柔软硬度、更高熔点与更稳定加工性能，让产品同时拥有舒适触感与卓越制造表现。</p><div className="heat-test"><div className="fail"><small>低熔点材料<br/>DF640 / ENGAGE 8842</small><div className="sample-image warped"><i/><i/></div><b>&lt; 50°C</b><em>容易发生二次热收缩、<br/>翘曲及外观不一致</em></div><span>加工温度<br/><strong>&gt;50°C →</strong><i>层压 / 后加工温度</i></span><div className="pass"><small>IUS–4065（约 64°C）</small><div className="sample-image stable"><i/></div><b>≈ 64°C</b><em>✓ 尺寸稳定性优异<br/>✓ 产品品质一致<br/>✓ 良率更高</em></div></div></div></div>
 <div className="performance"><div><span className="detail-label">PERFORMANCE COMPARISON</span><h3>材料性能对比</h3><div className="table-wrap"><table><thead><tr><th>性能 / Property</th><th>测试标准</th><th>DF640</th><th>ENGAGE 8842</th><th>IUS–4065</th></tr></thead><tbody><tr><td>硬度 Shore A</td><td>ASTM D2240</td><td>54–56</td><td>54–56</td><td>40</td></tr><tr><td>熔点 °C</td><td>DSC</td><td>&lt; 50</td><td>&lt; 50</td><td>≈ 64</td></tr><tr><td>热收缩风险</td><td>内部测试</td><td className="bad">高</td><td className="bad">高</td><td className="good">低</td></tr><tr><td>尺寸稳定性</td><td>内部测试</td><td className="bad">低</td><td className="bad">低</td><td className="good">高</td></tr><tr><td>柔软触感</td><td>内部评估</td><td className="rating-bad">★★★★☆</td><td className="rating-bad">★★★★☆</td><td className="good">★★★★★</td></tr><tr><td>加工稳定性</td><td>内部评估</td><td className="rating-bad">★★★☆☆</td><td className="rating-bad">★★★☆☆</td><td className="good">★★★★☆</td></tr></tbody></table></div></div><div className="advantages"><span className="detail-label">PRODUCT ADVANTAGES</span><h3>五项核心优势</h3>{[["01","超柔软触感","Shore A 40，触感舒适细腻"],["02","更高熔点","约 64°C，降低二次热收缩风险"],["03","卓越尺寸稳定","减少翘曲，尺寸更可控"],["04","更高良率","加工窗口稳定，减少次品"],["05","适用高性能应用","满足更高耐热与稳定性要求"]].map(x=><div className="advantage" key={x[0]}><b>{x[0]}</b><span>{x[1]}<small>{x[2]}</small></span></div>)}</div></div>
</section>
<section className="industries shell" id="industries"><div className="section-title"><span>02 — APPLICATIONS</span><h2>材料性能，落地于<br/>每一个真实场景</h2></div><div className="industry-list">{industries.map((x,i)=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p><span>↗</span>{i===0&&<div className="shoe">◒</div>}</article>)}</div></section>
<section className="rd" id="rd"><div className="shell"><div className="rd-copy"><span>03 — CUSTOM DEVELOPMENT</span><h2>从一个需求，<br/>到一种新材料</h2><p>研发工程师与您的产品团队直接协作，围绕硬度、颜色、密度、熔点、力学性能与加工窗口进行配方开发。</p><a href="#contact">启动定制项目 ↗</a></div><div className="rd-image"><img src="https://imp-umr5223.cnrs.fr/wp-content/uploads/2024/01/IMP-ingenierie-des-materiaux-polymeres-umr-cnrs-5223-reverse.jpg" alt="材料研发实验室"/><div><span>01 需求分析</span><span>02 配方开发</span><span>03 样品测试</span><span>04 批量生产</span></div></div></div></section>
<section className="factory shell" id="factory"><div className="factory-photo"><img src="https://www.ct-ipc.com/wp-content/uploads/2022/10/FDM_003-1024x683.jpg" alt="高分子材料挤出生产线"/><span>PRODUCTION / LAB / QUALITY</span></div><div className="factory-copy"><span>04 — FACTORY CAPABILITY</span><h2>研发与制造，<br/>在同一套质量体系内</h2><p>从原料检验、配方混炼到造粒与出厂检测，全流程数据化管理。让实验室性能稳定复现于每一批量产订单。</p><ul><li>双螺杆精密混炼与造粒</li><li>物性、老化与阻燃测试</li><li>批次 COA 与全流程追溯</li><li>OEM / ODM 柔性生产</li></ul></div></section>
<section className="faq shell"><div><span>05 — FAQ</span><h2>合作前，您可能<br/>想了解这些</h2></div><div>{faq.map((q,i)=><button onClick={()=>setOpen(open===i?-1:i)} key={q}><b>0{i+1}</b><span>{q}{open===i&&<small>{i===0?"支持。我们可提供实验室样、试产样及量产验证，具体起订量由材料体系决定。":"工程团队会根据目标参数与应用要求，提供明确的评估与项目计划。"}</small>}</span><i>{open===i?"−":"+"}</i></button>)}</div></section>
<section className="cta" id="contact"><div className="shell"><span>READY TO BUILD WHAT'S NEXT?</span><h2>让下一款产品，<br/>从更好的材料开始。</h2><p>Tell us your requirements. Our material engineer will reply within 24 hours.</p><button onClick={()=>toast("询盘入口已打开")}>联系材料工程师 ↗</button></div></section>
<footer className="footer shell"><a className="logo" href="#top"><i>R</i><span>原料网站<small>ADVANCED MATERIALS</small></span></a><p>Advanced thermoplastic material solutions for global manufacturing.</p><div><a href="#materials">Materials</a><a href="#rd">R&D</a><a href="#factory">Factory</a><a href="#contact">Contact</a></div><small>© 2026 原料网站. All rights reserved.</small></footer>{msg&&<div className="toast">✓ {msg}</div>}
</main>}
